apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trees
spec:
  rules:
  - host: local.ecosia.org
    http:
      paths:
      - path: /
        backend:
          serviceName: trees
          servicePort: 80